### ISSUE TITLE
Question about model

### ISSUE THREAD

**Issue by fatbao55** [huangyangyi/TeCH#1]
Dear authors, 

thanks for the great work! I would like to check if the approach is only generated from text prompts (text-to-3d similar to dreamfusion) or does it also take image as input (image-to-3d with text prompts similar to zero123/ magic123)?

**Comment by YuliangXiu** [comment]
Thanks for asking, TeCH takes **both** image and prompt for reconstruction, and the prompt is derived from the input image via VQA model. It's closer to Magic123.

**Comment by huangyangyi** [comment]
> Thanks so much for the clarification! Is there an estimated date for the code release?

Thanks for your interests! We plan to release the code in October.

**Comment by wagnerponciano** [comment]
> > Muito obrigado pelo esclarecimento! Existe uma data estimada para o lançamento do código?
> 
> Obrigado pelo seu interesse! Planejamos lançar o código em outubro.

Can we put it to test on colab?]
