### ISSUE TITLE
Where is the "smplx_vert_segmentation.json" file?

### ISSUE THREAD

**Issue by Subin-Kim46** [huangyangyi/TeCH#10]
Hi,
Thank you for your excellent investigation.
I got some error.

I didn't find "smplx_vert_segmentation.json" file. 
https://github.com/huangyangyi/TeCH/blob/dc2118b511545f2e67a70fb7034e4ecc0d1b0d31/utils/body_utils/postprocess.py#L91C4-L91C67

**Comment by huangyangyi** [comment]
You can find it here: https://github.com/zkf1997/COINS/blob/main/configuration/smplx_vert_segmentation.json
