### ISSUE TITLE
GlCheckError raise GLError(OpenGL.error.GLError: GLError( err = 1286, description = b'invalid framebuffer operation', baseOperation = glClear, cArguments = (16640,))

### ISSUE THREAD

**Issue by Subin-Kim46** [huangyangyi/TeCH#11]
Hi,
Thank you for your excellent investigation.

I tried this code "python utils/body_utils/postprocess.py"

I got some error at this code. 
https://github.com/huangyangyi/TeCH/blob/dc2118b511545f2e67a70fb7034e4ecc0d1b0d31/utils/body_utils/lib/common/render_pyrender.py#L141

So, I found this error and solution. 
https://github.com/mkocabas/VIBE/issues/47#issuecomment-1589209946

Then, I changed codes like

def render_scene(self, scene):
        renderer = pyrender.OffscreenRenderer(self.size * 8, self.size * 8)
        color, depth = renderer.render(scene, flags=pyrender.constants.RenderFlags.SKIP_CULL_FACES | 
        pyrender.constants.RenderFlags.ALL_SOLID | pyrender.constants.RenderFlags.SKIP_CULL_FACES)
        renderer.delete()
        return color, depth
...
color, depth = self.render_scene(scene)

But, I got same error...

**Comment by xyIsHere** [comment]
I got a segmentation fault (core dumped) here. Any suggestion for this error? By the way, what's the python version for this code?

Thanks!

**Comment by Subin-Kim46** [comment]
My Environment:
python : 3.8.10

**Comment by Subin-Kim46** [comment]
def __init__(self, size=512, ssaa=8, device=torch.device("cuda:0")):

@xyIsHere I changed the value of ssaa from 8 to 4. Then, i got mesh in various poses.

**Comment by xyIsHere** [comment]
> https://github.com/huangyangyi/TeCH/blob/dc2118b511545f2e67a70fb7034e4ecc0d1b0d31/utils/body_utils/lib/common/render_pyrender.py#L51
> 
> Changed : def **init**(self, size=512, ssaa=4, device=torch.device("cuda:0")):
> 
> @xyIsHere I changed the value of ssaa from 8 to 4. Then, i got mesh in various poses.

Thank you so much! The solution is very useful!

**Comment by AlbertHuyb** [comment]
So does this error happen due  to super high resolution when rendering a lot of triangles? In my case I need to modify the `size` and `ssaa` variables to smaller values.
