### ISSUE TITLE
'utf-8' codec can't decode byte 0xff error

### ISSUE THREAD

**Issue by youssef-shaban** [huangyangyi/TeCH#12]
Hi, I am trying to run you code as instruction but after installing everything and trying to run on a sample, I face this error and can't find a solution
![Screenshot 2023-11-23 220049](https://github.com/huangyangyi/TeCH/assets/85808789/c371824d-a1b4-4e58-97d9-0df777afc6d8)

**Comment by huangyangyi** [comment]
I am not sure about this problem, could you please show which file the code is trying to load?

**Comment by w1049** [comment]
I solved this by using .png file instead of .jpg.
