### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for AutoencoderKL

### ISSUE THREAD

**Issue by xx674967** [huangyangyi/TeCH#13]
Hi , Thank you for open-sourcing this project. I met an issue while running conert_ldm_to_diffusers.py, as shown in the picture. 
![MicrosoftTeams-image (2)](https://github.com/huangyangyi/TeCH/assets/26277179/0378097e-eb55-46a1-bb13-880ba22a53db)

It seems that the parameter names from the previous fine-tuning step do not match the VAE model. In your [code,](https://github.com/huangyangyi/TeCH/blob/main/utils/ldm_utils/convert_ldm_to_diffusers.py#L119) . Can this issue be addressed by modifying the names at this point? I look forward to your reply.

**Comment by 1406428260** [comment]
I have same question!

**Comment by 1406428260** [comment]
def renew_vae_attention_paths(old_list, n_shave_prefix_segments=0):
    """
    Updates paths inside attentions to the new naming scheme (local renaming)
    """
    mapping = []
    for old_item in old_list:
        new_item = old_item

        new_item = new_item.replace("norm.weight", "group_norm.weight")
        new_item = new_item.replace("norm.bias", "group_norm.bias")

        new_item = new_item.replace("q.weight", "to_q.weight")
        new_item = new_item.replace("q.bias", "to_q.bias")

        new_item = new_item.replace("k.weight", "to_k.weight")
        new_item = new_item.replace("k.bias", "to_k.bias")

        new_item = new_item.replace("v.weight", "to_v.weight")
        new_item = new_item.replace("v.bias", "to_v.bias")

        new_item = new_item.replace("proj_out.weight", "to_out.0.weight")
        new_item = new_item.replace("proj_out.bias", "to_out.0.bias")

        new_item = shave_segments(new_item, n_shave_prefix_segments=n_shave_prefix_segments)

        mapping.append({"old": old_item, "new": new_item})

    return mapping

end of def convert_ldm_vae_checkpoint add :
fix_key = [x for x in new_checkpoint if 'mid_block.attentions' in x]
    for key in fix_key:
        if len(new_checkpoint[key].shape) == 4:
            new_checkpoint[key] = torch.squeeze(new_checkpoint[key])
    return new_checkpoint

**Comment by huangyangyi** [comment]
Hi, that should be a problem related to using different `diffusers` version. You can solve this problem by modifying code in `utils/ldm_utils/convert_ldm_to_diffusers.py`, changing the parameter keys from `query`, `key`, `value` and `proj_attn` to `to_q`, `to_k`, `to_v` and `to_out`.

**Comment by cwwjyh** [comment]
> > Hi, that should be a problem related to using different `diffusers` version. You can solve this problem by modifying code in `utils/ldm_utils/convert_ldm_to_diffusers.py`, changing the parameter keys from `query`, `key`, `value` and `proj_attn` to `to_q`, `to_k`, `to_v` and `to_out`.
> 
> I modified the code as you said above, but I encountered a question as below. Can you give me some advice? Thank you! ![1704883460843](https://private-user-images.githubusercontent.com/26154160/295538527-2187c9f6-1dc2-4e13-80e8-e3a017c53ac3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTM5NjcsIm5iZiI6MTcwNDg5MzY2NywicGF0aCI6Ii8yNjE1NDE2MC8yOTU1Mzg1MjctMjE4N2M5ZjYtMWRjMi00ZTEzLTgwZTgtZTNhMDE3YzUzYWMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEzMzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczODM3MGQxODJiZTJhZDJiNzkyYjRhYjE4OTA0YTdkNDFjY2U1YzE0MjMxYTYzY2IxN2U1NTM5YzA3YjY5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dil4T069WFK-0vYDQvgQhRHAkeLou3Uuxu_5Bm7N9pc) When I use **to_out.0** to replace **proj_attn** encounter the below issue. ![1704884310094](https://private-user-images.githubusercontent.com/26154160/295542452-e7a543dc-931e-455c-acfe-3be6f637b9ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTM5NjcsIm5iZiI6MTcwNDg5MzY2NywicGF0aCI6Ii8yNjE1NDE2MC8yOTU1NDI0NTItZTdhNTQzZGMtOTMxZS00NTVjLWFjZmUtM2JlNmY2MzdiOWVjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEzMzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YTM1OWM0MTEwNWM2MjY0ZjRiYWQ5OTIwYzFmMTlmZjJhYWNlMzYyNjVlM2FjNWY2OWYwNzJmZWI0MTcwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xdEuZwfvFD060U8KZ36xv7M8uebZM7SLcqpjizW4sJ0)

I address this issue when I install **diffusers==0.15.0**
