### ISSUE TITLE
weird geometry & texture on leg

### ISSUE THREAD

**Issue by ZunDuJiaDu** [huangyangyi/TeCH#14]
![image](https://github.com/huangyangyi/TeCH/assets/143506638/670783bc-edbb-4559-9750-300cdfc43dc2)
Anyone met the same weird geometry and texture on the leg?

I guess this is caused by the mismatch of SMPLX model and provided images. Do you have suggestions?

**Comment by huangyangyi** [comment]
Yes, this can happen when SMPL-X estimates are inaccurate. You can try passing a extra loss mask to mask out all the normal regularization loss and reconstruction losses in the incorrect area, in this part of the code https://github.com/huangyangyi/TeCH/blob/5efe7d6173e3b4c113697d1296aafb766378026a/core/lib/trainer.py#L242-L246

**Comment by Subin-Kim46** [comment]
[Origin image]
![image](https://github.com/huangyangyi/TeCH/assets/76643618/bb7735cf-b2a0-4b5e-a426-aea45741e78f)

[Mesh]
![image](https://github.com/huangyangyi/TeCH/assets/76643618/5ec18850-6517-4827-abca-f930963aa3c1)

Thank you so much. 
I want an outstretched leg on mesh. But, I got a folded leg like image.
Any suggestion for this error?

**Comment by huangyangyi** [comment]
The SMPL-X pose estimation method (PIXIE) we use often encounter such problem, you can try to replace the smplx estimation with Pymaf-x or other more advanced methods

**Comment by YuliangXiu** [comment]
@huangyangyi @Subin-Kim46 @ZunDuJiaDu 

The issue of bending legs get resolved finally, please check out [tricks.md/bending-legs](https://github.com/YuliangXiu/ECON/blob/master/docs/tricks.md#bending-legs).

**Comment by huangyangyi** [comment]
> @huangyangyi @Subin-Kim46 @ZunDuJiaDu
> 
> The issue of bending legs get resolved finally, please check out [tricks.md/bending-legs](https://github.com/YuliangXiu/ECON/blob/master/docs/tricks.md#bending-legs).

Great work! Thank you Yuliang👍
