### ISSUE TITLE
question about scripts/run.sh

### ISSUE THREAD

**Issue by cwwjyh** [huangyangyi/TeCH#17]
Hello, this is a good work!
I ran "sh scripts/run.sh  input/g.png  exp/examples/name", but encountered an issue as below:
![image](https://github.com/huangyangyi/TeCH/assets/26154160/50996ce3-9a25-450a-8b4e-0147d20f7b6b)

When running: python utils/ldm_utils/main.py -t --data_root exp/examples/name/png/ --logdir exp/examples/name/ldm/ --reg_data_root data/dreambooth_data/class_man_images/ --bg_root data/dreambooth_data/bg_images/ --class_word man --no-test --gpus 2,3

Can you give me some advice? Thank you very much!

**Comment by cwwjyh** [comment]
> Hello, this is a good work! I ran "sh scripts/run.sh input/g.png exp/examples/name", but encountered an issue as below: ![image](https://private-user-images.githubusercontent.com/26154160/293020968-50996ce3-9a25-450a-8b4e-0147d20f7b6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzYxNDMsIm5iZiI6MTcwMzY3NTg0MywicGF0aCI6Ii8yNjE1NDE2MC8yOTMwMjA5NjgtNTA5OTZjZTMtOWEyNS00NTBhLThiNGUtMDE0N2QyMGY3YjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDExMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzhmMDNhZjdkMjhmMzczZDc4MjA3Y2UwZGFjNWNiOWMxNjQ3YTg1YzE2NmZmNTE0YzhhMzI0N2RlZWYyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yv2r0vIkfRkcHUU1JiQcb0Xr_qHrgIM4eXLhyrE6ubg)
> 
> When running: python utils/ldm_utils/main.py -t --data_root exp/examples/name/png/ --logdir exp/examples/name/ldm/ --reg_data_root data/dreambooth_data/class_man_images/ --bg_root data/dreambooth_data/bg_images/ --class_word man --no-test --gpus 2,3
> 
> Can you give me some advice? Thank you very much!



Hi, i have solved this problem

**Comment by RageshAntonyHM** [comment]
@cwwjyh How did you fix it?

**Comment by RageshAntonyHM** [comment]
@cwwjyh 
Thanks. As per the example, `sh scripts/run.sh input/examples/name.img exp/examples/name` ....

where is the folder and files located ?

Are, do I need to provide it myself ?

And what is in your g.png ? A human pose ?

**Comment by glorioushonor** [comment]
> > @cwwjyh How did you fix it?
> 
> Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)

Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.

**Comment by cwwjyh** [comment]
> > > @cwwjyh How did you fix it?
> > 
> > 
> > Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)
> 
> Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.

I use 32GB of VRAM and reset batch_size=6 in **test.yaml**. If you use 24GB, you can try to set batch_size=1.

**Comment by glorioushonor** [comment]
> > > > @cwwjyh How did you fix it?
> > > 
> > > 
> > > Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)
> > 
> > 
> > Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.
> 
> I use 32GB of VRAM and reset batch_size=6 in **test.yaml**. If you use 24GB, you can try to set batch_size=1.

Hello, I would like to double-check one thing. Since I couldn't find the test.yaml file, are you referring to the v1-finetune.yaml file?
![image](https://github.com/huangyangyi/TeCH/assets/120625228/708743ea-8d27-441b-813b-80aff35db4cc)
![image](https://github.com/huangyangyi/TeCH/assets/120625228/426b58f2-fe88-49a1-be95-b03d8a690072)

**Comment by cwwjyh** [comment]
> > > > > @cwwjyh How did you fix it?
> > > > 
> > > > 
> > > > Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)
> > > 
> > > 
> > > Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.
> > 
> > 
> > I use 32GB of VRAM and reset batch_size=6 in **test.yaml**. If you use 24GB, you can try to set batch_size=1.
> 
> Hello, I would like to double-check one thing. Since I couldn't find the test.yaml file, are you referring to the v1-finetune.yaml file? ![image](https://private-user-images.githubusercontent.com/120625228/299230995-708743ea-8d27-441b-813b-80aff35db4cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODMwODEsIm5iZiI6MTcwNjA4Mjc4MSwicGF0aCI6Ii8xMjA2MjUyMjgvMjk5MjMwOTk1LTcwODc0M2VhLThkMjctNDQxYi04MTNiLTgwYWZmMzVkYjRjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNzUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjkzMmQ4ZWVjY2UzYmQ4N2YwMTMwYmE4ZTk2ODlhNDY5MmMyYjNjNGM0ZGQ0NTE2NDZhYzQyMjM0MGIyYWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YKSAsumlBzI_OAhVyO0QvkLibGy1AycsfyjhCxIDDNs) ![image](https://private-user-images.githubusercontent.com/120625228/299233217-426b58f2-fe88-49a1-be95-b03d8a690072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODMwODEsIm5iZiI6MTcwNjA4Mjc4MSwicGF0aCI6Ii8xMjA2MjUyMjgvMjk5MjMzMjE3LTQyNmI1OGYyLWZlODgtNDlhMS1iZTk1LWIwM2Q4YTY5MDA3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNzUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTBkMTRhNTM1NmUwZDMzNGM0NWIyODY3M2FkYTUyZTZkYTdjMjdjZDliM2NmOTkzOTQyODA0MWZkNGE3N2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4MX8usi3MR8ejEjA-7-u0jgY8J0oRLa5FzvlxDZYaM)

![image](https://github.com/huangyangyi/TeCH/assets/26154160/8a6538e3-2e9a-498a-89f0-ed55a3c4dfec)

**Comment by glorioushonor** [comment]
> > > > > > @cwwjyh How did you fix it?
> > > > > 
> > > > > 
> > > > > Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)
> > > > 
> > > > 
> > > > Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.
> > > 
> > > 
> > > I use 32GB of VRAM and reset batch_size=6 in **test.yaml**. If you use 24GB, you can try to set batch_size=1.
> > 
> > 
> > Hello, I would like to double-check one thing. Since I couldn't find the test.yaml file, are you referring to the v1-finetune.yaml file? ![image](https://private-user-images.githubusercontent.com/120625228/299230995-708743ea-8d27-441b-813b-80aff35db4cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODMwODEsIm5iZiI6MTcwNjA4Mjc4MSwicGF0aCI6Ii8xMjA2MjUyMjgvMjk5MjMwOTk1LTcwODc0M2VhLThkMjctNDQxYi04MTNiLTgwYWZmMzVkYjRjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNzUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjkzMmQ4ZWVjY2UzYmQ4N2YwMTMwYmE4ZTk2ODlhNDY5MmMyYjNjNGM0ZGQ0NTE2NDZhYzQyMjM0MGIyYWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YKSAsumlBzI_OAhVyO0QvkLibGy1AycsfyjhCxIDDNs) ![image](https://private-user-images.githubusercontent.com/120625228/299233217-426b58f2-fe88-49a1-be95-b03d8a690072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODMwODEsIm5iZiI6MTcwNjA4Mjc4MSwicGF0aCI6Ii8xMjA2MjUyMjgvMjk5MjMzMjE3LTQyNmI1OGYyLWZlODgtNDlhMS1iZTk1LWIwM2Q4YTY5MDA3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNzUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTBkMTRhNTM1NmUwZDMzNGM0NWIyODY3M2FkYTUyZTZkYTdjMjdjZDliM2NmOTkzOTQyODA0MWZkNGE3N2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4MX8usi3MR8ejEjA-7-u0jgY8J0oRLa5FzvlxDZYaM)
> 
> ![image](https://private-user-images.githubusercontent.com/26154160/299235024-8a6538e3-2e9a-498a-89f0-ed55a3c4dfec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODM5MTIsIm5iZiI6MTcwNjA4MzYxMiwicGF0aCI6Ii8yNjE1NDE2MC8yOTkyMzUwMjQtOGE2NTM4ZTMtMmU5YS00OThhLTg5ZjAtZWQ1NWEzYzRkZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4MDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OTgxNzdmMmJjMzk1NDIxMWJkZTdhZmUxYjg4NTQ5YjE5NDQ4MWQwNDRjNTQ3MWY5MGNlOTRjMmEyYzMwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sq61Ncgw1zS3shpopRbEA-F7Gdj4aWv_ONLnYE_LLWc)

Haha, perhaps you made a mistake. This work is from TeCH, not HumanGaussian.

**Comment by cwwjyh** [comment]
> > > > @cwwjyh How did you fix it?
> > > 
> > > 
> > > Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)
> > 
> > 
> > Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.
> 
> I use 32GB of VRAM and reset batch_size=6 in **test.yaml**. If you use 24GB, you can try to set batch_size=1.

haha, sorry. I use 2GPU 32GB of VRAM in TeCH project.  Then it can work.

**Comment by glorioushonor** [comment]
> > > > > @cwwjyh How did you fix it?
> > > > 
> > > > 
> > > > Because the GPU setting is wrong, it can run after modification. ![image](https://private-user-images.githubusercontent.com/26154160/293351848-5b32c1cb-b91a-414d-b3e5-9312c7728c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyNjksIm5iZiI6MTcwNjA2NDk2OSwicGF0aCI6Ii8yNjE1NDE2MC8yOTMzNTE4NDgtNWIzMmMxY2ItYjkxYS00MTRkLWIzZTUtOTMxMmM3NzI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY1MjllNzY0MTBlMzQyZGJiMDE4MGMzMzc5YWE1NGU1MTRhOGYxNTRhMWY2OTZlZjhlMDQ2ZmYwM2U0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyZMKE21wXq5QjHJ4EVMG-pvo_pXqJg0a16XHlVszQM)
> > > 
> > > 
> > > Hello, may I ask how much memory each of your GPUs has? I encountered Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM. Thanks.
> > 
> > 
> > I use 32GB of VRAM and reset batch_size=6 in **test.yaml**. If you use 24GB, you can try to set batch_size=1.
> 
> haha, sorry. I use 2GPU 32GB of VRAM in TeCH project. Then it can work.


By the way, may I ask if the final output file `000_texture.obj` contains color? My `000_texture.obj `file is the same as `000_geometry.obj`, both lacking color. When I proceed with the optional code below, the program becomes stuck.
`python cores/main.py --config configs/tech_texture_export.yaml --exp_dir $EXP_DIR --sub_name $SUBJECT_NAME --test`
And I'm not sure if running the final script generates an OBJ file with color. 
![image](https://github.com/huangyangyi/TeCH/assets/120625228/6979c1ab-6720-4330-b001-aed4ec849541)

**Comment by cwwjyh** [comment]
@glorioushonor 
![image](https://github.com/huangyangyi/TeCH/assets/26154160/6cf631cf-8cac-4453-abc1-6b0b8f6a514f)
I get an error when I run this line, so I'm not sure what the end result will be.

**Comment by glorioushonor** [comment]
> @glorioushonor ![image](https://private-user-images.githubusercontent.com/26154160/299513360-6cf631cf-8cac-4453-abc1-6b0b8f6a514f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDg2OTIsIm5iZiI6MTcwNjE0ODM5MiwicGF0aCI6Ii8yNjE1NDE2MC8yOTk1MTMzNjAtNmNmNjMxY2YtOGNhYy00NDUzLWFiYzEtNmIwYjhmNmE1MTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAyMDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTY2MDJhZTAyMzljNTk4Yjg5ZmU2NDVlZDkyOGI3OTAwZWYwOTE1NTlkNDc4MDBlZjUyMjY2ZDgzYmZkMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.En_XqBnZSghyVNDWuzgCJ-jvJDJRM_Bb7Hm6mRZcGSg) I get an error when I run this line, so I'm not sure what the end result will be.

What problem have you encountered? Maybe I can help you.

**Comment by cwwjyh** [comment]
@glorioushonor 
![image](https://github.com/huangyangyi/TeCH/assets/26154160/3c62e1ac-1d82-495a-903c-e241f3e5a669)
I encounter this problem. The command in the red box doesn't seem to run, it then just runs the next line, resulting in no g_geometry.obj file.

**Comment by glorioushonor** [comment]
> @glorioushonor ![image](https://private-user-images.githubusercontent.com/26154160/299524116-3c62e1ac-1d82-495a-903c-e241f3e5a669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTI0NjQsIm5iZiI6MTcwNjE1MjE2NCwicGF0aCI6Ii8yNjE1NDE2MC8yOTk1MjQxMTYtM2M2MmUxYWMtMWQ4Mi00OTVhLTkwM2MtZTI0MWYzZTVhNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAzMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmQ0MzA1MzQyODI1ZWFiOTA4MGZkZTVkMzIwM2EzZDAyNzRiNmVhNDhmNjBhNzYyY2I3MWM2OTM1ZGQ0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.atbDQDUtpTPLM1s9eQC-wWAGxQ-21vWQ06DjO_q0Dv4) I encounter this problem. The command in the red box doesn't seem to run, it then just runs the next line, resulting in no g_geometry.obj file.

I suggest commenting out the commands after this line of code in the script first to obtain the error message and locate the issue.
![image](https://github.com/huangyangyi/TeCH/assets/120625228/5f994025-f246-474c-a032-71ff61414780)
