### ISSUE TITLE
I'm stuck at this step”export textured mesh with UV map, using atlas for UV unwraping.“

### ISSUE THREAD

**Issue by surheaven** [huangyangyi/TeCH#18]
![image](https://github.com/huangyangyi/TeCH/assets/89247297/284ea0df-4569-4438-b962-4cb8b1ca1466)
This step lasted an hour and didn't go any further.  Hardware runs are available here.
![image](https://github.com/huangyangyi/TeCH/assets/89247297/b51f9066-c40c-4431-bcfe-c257b62fbf1f)
The input image is shown below:
![test](https://github.com/huangyangyi/TeCH/assets/89247297/c4a402a3-c674-4fbf-93ea-cf84d08d0b52)

**Comment by glorioushonor** [comment]
> ![image](https://private-user-images.githubusercontent.com/89247297/294836403-284ea0df-4569-4438-b962-4cb8b1ca1466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTczNDEsIm5iZiI6MTcwNjA5NzA0MSwicGF0aCI6Ii84OTI0NzI5Ny8yOTQ4MzY0MDMtMjg0ZWEwZGYtNDU2OS00NDM4LWI5NjItNGNiOGIxY2ExNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDExNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZGFhYjg1MzI5ZmY0NzUyYWU5MDRlODk0MTU4OWU0NzViMjM0NWI1ZWFjZDgxM2UxYmZkNzQxYzgyOWM0YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vMSesPWZUuEOVzpSOOuMeCkEq7ThyaZcYbBKEOuiSvY) This step lasted an hour and didn't go any further. Hardware runs are available here. ![image](https://private-user-images.githubusercontent.com/89247297/294836695-b51f9066-c40c-4431-bcfe-c257b62fbf1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTczNDEsIm5iZiI6MTcwNjA5NzA0MSwicGF0aCI6Ii84OTI0NzI5Ny8yOTQ4MzY2OTUtYjUxZjkwNjYtYzQwYy00NDMxLWJjZmUtYzI1N2I2MmZiZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDExNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDIyOGZkOWNlYWY2ZjEzYWQyYzYzMzNhYmEzZDRhN2FiMzRkYTU1NDgzNGFhMDU2NWJiZjMwY2JjNGM5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jDZEVddhRO6nUAusaXT2Qi3i3QGzwRF0kPL6P1skoW4) The input image is shown below: ![test](https://private-user-images.githubusercontent.com/89247297/294836777-c4a402a3-c674-4fbf-93ea-cf84d08d0b52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTczNDEsIm5iZiI6MTcwNjA5NzA0MSwicGF0aCI6Ii84OTI0NzI5Ny8yOTQ4MzY3NzctYzRhNDAyYTMtYzY3NC00ZmJmLTkzZWEtY2Y4NGQwOGQwYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDExNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZmFiZTljMjYzYWJiMTdjODNlODI1MTA0NzZiMzA5MzhiMzQyMWMyNGJmZmMwNDIzMjZjMzg1MDc1OTZmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9gz4WdaZbv1LSBYD-PtHgM9AiS5FbPZcK4Ke5W2kdQ8)

Me too! Haveyou solved the problem?

**Comment by YuliangXiu** [comment]
I have updated the atlas params in [commit#/f84972](https://github.com/huangyangyi/TeCH/commit/f84972caf00e584efaf986813803b2b469135451)

**Comment by liuxshisan** [comment]
Me too! Haveyou solved the problem?

**Comment by YuliangXiu** [comment]
@lxfyn 

1. downsample the geometry produced by Geo-SDS, see [mesh_util.py#L405](https://github.com/YuliangXiu/TeCH/blob/yxiu/utils/body_utils/lib/dataset/mesh_util.py#L405) and [postprocess.py#L265](https://github.com/YuliangXiu/TeCH/blob/yxiu/utils/body_utils/postprocess.py#L265)
2. update the UV atlas params, see [commit#f84972](https://github.com/huangyangyi/TeCH/commit/f84972caf00e584efaf986813803b2b469135451)

**Comment by liuxshisan** [comment]
> @lxfyn
> 
> 1. 对 Geo-SDS 生成的几何图形进行下采样，参见 [mesh_util.py#L405](https://github.com/YuliangXiu/TeCH/blob/yxiu/utils/body_utils/lib/dataset/mesh_util.py#L405) 和 [postprocess.py#L265](https://github.com/YuliangXiu/TeCH/blob/yxiu/utils/body_utils/postprocess.py#L265)
> 2. 更新 UV 图集参数，参见 [commit#f84972](https://github.com/huangyangyi/TeCH/commit/f84972caf00e584efaf986813803b2b469135451)

@YuliangXiu thank you for your reply! But I updated the above files as you said but still no success
