### ISSUE TITLE
Questions about GPUs

### ISSUE THREAD

**Issue by glorioushonor** [huangyangyi/TeCH#21]
In the process of fine-tuning Dreambooth, is it necessary for each GPU to have 32GB of VRAM? I encounter Out-Of-Memory (OOM) errors when running the code on a server with 4 GPUs, each having 24GB of VRAM.

**Comment by huangyangyi** [comment]
Hi, you can refer to [this issue](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/issues/70) and try adjusting the batchsize

**Comment by wyiguanw** [comment]
@glorioushonor Hi, have you been able to run on 24G GPUS? if you do, could you let me know how you did that? I tried setting all batch-size to 1 , and adding those arguments in the command line, seems not working.

**Comment by Kenn3o3** [comment]
@glorioushonor Hi, have you been able to run on 24G GPUS? if you do, could you let me know how you did that? I tried setting all batch-size to 1 , and adding those arguments in the command line, seems not working.
