### ISSUE TITLE
How ECON helps TeCH？

### ISSUE THREAD

**Issue by glorioushonor** [huangyangyi/TeCH#22]
Hello. I'd like to inquire about how ECON's d-BINI provides assistance to Tech during the post-processing stage.
![image](https://github.com/huangyangyi/TeCH/assets/120625228/65e56e8e-54d2-4bc9-81bd-04c51c354e1d)

**Comment by donghaoye** [comment]
Good Question.

**Comment by huangyangyi** [comment]
Hi, this post-processing steps simply refine the SMPL-X meshes to better aligned with the geometry stage result of TeCH, for later steps of replacing hands geometry with SMPL-X hands
