### ISSUE TITLE
Why is dilated_mesh.obj so much smaller than the original smpl-x?

### ISSUE THREAD

**Issue by surheaven** [huangyangyi/TeCH#26]
![image](https://github.com/huangyangyi/TeCH/assets/89247297/ac8cfb73-76fa-452d-9fec-102670af3e21)

**Comment by huangyangyi** [comment]
Hi, the dilated outer shell is constructed in the normalized space, so it is usually smaller than the original SMPL mesh. While exporting the geometry result, TeCH will perform an inverse operation to transform the mesh back to the original space.

**Comment by surheaven** [comment]
Thanks a lot !!!
