### ISSUE TITLE
OPENAI_AI_KEY

### ISSUE THREAD

**Issue by 12awei** [huangyangyi/TeCH#29]
![image](https://github.com/huangyangyi/TeCH/assets/95277262/04e8c2c8-c94b-4a0d-8951-4a7b9b917bbd)
May I ask how to solve this problem？

**Comment by NeuroLord** [comment]
Is it possible to find out how you solved the problem?

> ![image](https://private-user-images.githubusercontent.com/95277262/318247609-04e8c2c8-c94b-4a0d-8951-4a7b9b917bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTIzOTUsIm5iZiI6MTcxNTAxMjA5NSwicGF0aCI6Ii85NTI3NzI2Mi8zMTgyNDc2MDktMDRlOGMyYzgtYzk0Yi00YTBkLTg5NTEtNGE3YjliOTE3YmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE2MTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2ZlODdjZWJlNmFlNzgzNDI3M2I5NzQzOGQzZmM4OWNmYTRmM2MyNjNkNDY5NTgyMzlhNmQwYmVjNjkyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x0hHUkFaGugjf8r3CA0t9W0QR8EvrmFufvOaAzlO_zE) May I ask how to solve this problem？
