### ISSUE TITLE
Final output in .obj format with textures?

### ISSUE THREAD

**Issue by kashishnaqvi10** [huangyangyi/TeCH#3]
Hi, will the final object be in .obj format so that we can use them for animation purposes?

**Comment by YuliangXiu** [comment]
Yes, we have included the animation demo both in paper and video.

**Comment by kashishnaqvi101** [comment]
I meant, will the output be in .obj format ? or it is just a video generated?

**Comment by YuliangXiu** [comment]
It's in .obj format, with a skeleton inside which could drive the mesh with SMPL-X params.

**Comment by ZunDuJiaDu** [comment]
Hi there, I have successfully generated a 3D model. Under the folder 'texture‘, the generated video shows a textured 3D model. but when I import im_texture.obj under the folder 'obj' in blender, the texture is not displayed but only mesh. Do you have any suggestions?

**Comment by TharHtetAungg** [comment]
@ZunDuJiaDu If I am not wrong, I think they used vertex coloring for texture and you can only see that texture in Meshlab not blender.

**Comment by YuliangXiu** [comment]
@ZunDuJiaDu @TharHtetAungg 

Blender supports vertex-color node, see [vertex_paint](https://docs.blender.org/manual/en/latest/sculpt_paint/vertex_paint/index.html)

**Comment by TharHtetAungg** [comment]
@YuliangXiu your model didn't output texture.png right?

**Comment by Subin-Kim46** [comment]
So, how to load texture in Blender? I just import "--- _texture.obj"

**Comment by huangyangyi** [comment]
> So, how to load texture in Blender? My "--- _texture_export_albedo.png" color is gray. just one color but The video produced shows the colors well
@Subin-Kim46 
This is probably because `tech_texture_export.yaml` did not resume `tech_texture.yaml`'s training checkpoint. Please try modify `stage: texture_export` to `stage: texture` in `tech_texture_export.yaml` and export the textured mesh again.

**Comment by Anning-Hu** [comment]
Hi, how to animate the reconstructed avatar with SMPL-X motions like you did in the video?
