### ISSUE TITLE
runwayml/stable-diffusion-v1-5 Not Found

### ISSUE THREAD

**Issue by naruya** [huangyangyi/TeCH#38]
Thank you for sharing such great research and code!
It seems that the model in the following link is no longer available. Are there any alternative options?
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.ckpt

![スクリーンショット 2024-09-15 190125](https://github.com/user-attachments/assets/87985367-e5a5-4e81-a57e-c1dba1489835)

![スクリーンショット 2024-09-15 190857](https://github.com/user-attachments/assets/5740db71-6805-4a2b-8bfd-6277d0bc3833)

Also, when I ran wget, I was getting “401 Unauthorized”, so I added a header.

```diff
-wget 'https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.ckpt' -O data/dreambooth_data/v1-5-pruned.ckpt
+wget --header="Authorization: Bearer hf_xxxx" 'https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.ckpt' -O data/dreambooth_data/v1-5-pruned.ckpt
```

**Comment by huangyangyi** [comment]
Yes, unfortunately RunwayML has removed their huggingface model, you can find one re-uploaded repo to replace that. For example, this one: https://huggingface.co/benjamin-paine/stable-diffusion-v1-5.
Please feel free to reopen this issue if you have further inquiries.

**Comment by naruya** [comment]
Thank you!
