### ISSUE TITLE
yaml file

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [huangyangyi/TeCH#5]
Hi Yangyi,

Thanks for your excellent work. I wonder where I can find the [tech_texture_export.yaml](https://github.com/huangyangyi/TeCH/blob/dc65df7b7425d045b8451395184bfc6de8631001/scripts/run.sh#L36)

**Comment by huangyangyi** [comment]
Hi, thanks for you feedback! I have uploaded this yaml, or you can just set `save_uv: true` in `tech_texture.yaml`.
