### ISSUE TITLE
GPU memory limited

### ISSUE THREAD

**Issue by liustu** [huangyangyi/TeCH#6]
Hi, would there another solution for "Step 3: Finetune Dreambooth model (minimal GPU memory requirement: 2x32G): with only a single 3090 GPU?

**Comment by huangyangyi** [comment]
We plan to test how TeCH works with more efficient DreamBooth finetune strategies, but you can try it out yourself first by following [the examples in diffusers](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth).

**Comment by liustu** [comment]
ok,thank you.



---Original---
From: "Yangyi ***@***.***&gt;
Date: Tue, Oct 31, 2023 20:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huangyangyi/TeCH] GPU memory limited (Issue #6)




 
We plan to test how TeCH works with more efficient DreamBooth finetune strategies, but you can try it out yourself first by following the examples in diffusers.

**Comment by Xzy765039540** [comment]
I was run step 3 in two RTX 3090 by using half precision and apex amp_backend 
![微信截图_20231110111818](https://github.com/huangyangyi/TeCH/assets/91797762/dc02014d-250d-4f36-b896-7812ded02761)

**Comment by shenwenhao01** [comment]
> I was run step 3 in two RTX 3090 by using half precision and apex amp_backend ![微信截图_20231110111818](https://user-images.githubusercontent.com/91797762/281943646-dc02014d-250d-4f36-b896-7812ded02761.png)

Could you please show how to modify the code to implement the half precision training? I have tried to use apex amp in two GPU with 24GB each but it still goes out of memory.

**Comment by RichardChen20** [comment]
@Xzy765039540 Hi, can you provide more details about how to modify "v1-finetune_unfrozen.yaml" and the optimizer? I don't know where to put "mixed_precision: fp16" and I'm not sure if this param is correct. Thank you very much!
